language: node_js
node_js:
  - stable
addons:
  ssh_known_hosts: 47.99.143.70
before_install:
  - openssl aes-256-cbc -K $encrypted_c92ba44ece9b_key -iv $encrypted_c92ba44ece9b_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

install:
  - npm install

build:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@139.199.189.12:/usr/share/nginx/html/100-days-css-challenge
  on:
    branch: master
