language: node_js
node_js:
  - stable
cache: npm
branches:
  only:
    - master
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
# after_deploy:
#   provider: releases
#   api_key:
#     secure: LQr6u4mf0ia0RB6Py6TXHaWuFDZEb5Hfmp68MuenQbLMqbOZF1kvh1S/8GGhYbEhJlwvbrydAbBWj38dGQ7uwnV9qxnyESHls0T5sxN95B7vYBlHpOItfN3To6XF6fAT+S0h+8m3f5bQq+h//wf+3VZwR+Br8gt7/R4z1I08WqCOJG7cQYVOspK1Q8Iz+gjmffd7jCbx6JALoccklIzEca1Qaj3vhgCd4tB6aWQn7+crn9tlHj6ODaPDgk/4egwaRHVPlsbAxaw3W+fnu6ZYLF0fVN1tNXs3OfsYo6jTI6OFkeMvlOuOlUniiUwLrlKwjRUW+VPKtUdof34CPNQh+0+/LogVA7cHUZNypOY+xqe4SBzCV7KD9t5jfvaLhpmGxTO0LPjVF8PYt7CmWUvNtxGkrSYCMdug5aIHdW6jafMKa/kjmjArVMQrYxX5QIUdPhjYsCbYWcu+oc34hoH6QOOywdX2/cljZmhhP8887LaEG8yk9DnbK3OkQlFQoJuuUj0rmA3qGlSuLUMY+JziKYRAiK1h87BcGOFV63R2G6ZLJ2wLwfVF+OfRIkKRqkHZ3cGuyYucMU0Sz5nK2544YbXYYIyZWxCZn1kUtMaqXLpyZlob7Xg1VIWrJ0qMtSU1IYvxuyZIA4P+tGVN9QeMMSbfMNyAU053wG0xhUPK/uU=
#   on:
#     tags: true
