on:
  push:
    branches:
      - master
    paths:
      - "package.json"
      - "src/**"
      - "public/**"

name: Create Release

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Use Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build distribution if needed
        run: |
          npm i
          npm run build

      - name: Update dist folder to current repository
        run: |
          git config --local user.email "gemini0525@foxmail.com"
          git config --local user.name "funnypan"
          git add dist
          git commit -m "Auto commit version $(cat public/VERSION)"
          git push -f https://funnypan:$GITHUB_TOKEN@github.com/funnypan/100-days-css-challenge.git master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
